exports.home = require('./home.js')
exports.authenticate = require('./authenticate.js')
exports.authUrl = require('./authUrl.js')
exports.gaViews = require('./gaViews.js')
exports.gaSaveViews = require('./gaSaveViews.js')